AB#9260 Create Products (5-col promo) component
Sitecore/Sitecore.Demo.XMCloud.Verticals pull request #30
Opened 2024-04-23 12:09 UTC by chpa7

2024-04-23 16:31 UTC, adoprog requested changes

2024-04-23 16:31 UTC, adoprog commented on src/items/sxa-content/content/Verticals/Financial/Settings/Site Grouping/Financial.yml
> +  Value: "chpa-test-5-col-nf1qhuqnqks5t3n7jr3eaw-financial.vercel.app"
Please revert the hostname change

2024-04-23 16:31 UTC, adoprog commented on src/items/sxa-content/content/Verticals/Basic/Settings/Site Grouping/Basic.yml
> +  Value: "chpa-test-5-col-nf1qhuqnqks5t3n7jr3eaw-basic.vercel.app"
Please revert the hostname change

2024-04-23 16:31 UTC, adoprog commented on src/items/sxa-content/content/Verticals/Services/Settings/Site Grouping/Services.yml
> +  Value: "chpa-test-5-col-nf1qhuqnqks5t3n7jr3eaw-services.vercel.app"
Please revert the hostname change

2024-04-23 16:31 UTC, adoprog commented on src/items/sxa-content/content/Verticals/Financial/Home/finance-for-you/Data/Text 3.yml
> -    Fields:
Let's keep the sample text while we don't have real content.

2024-04-23 16:48 UTC, adoprog commented on src/components/collections.json
> +[
Ok to add Components, but let's not push them as changed every time, unless there is a change to actual components content.

2024-04-23 16:48 UTC, adoprog commented on src/items/sxa-content/content/Verticals/Financial/Home/Data/Five Column CTA 2.yml
> +﻿---
Do we need all these three items? Let's leave the one that is used by the rendering we have at home page.

2024-04-24 09:24 UTC, chpa7 commented
Reverted the "Demo Portal - automated items sync" commits.

2024-04-24 13:57 UTC, adoprog approved these changes

2024-04-24 13:58 UTC, merged